image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info
  Footer
  © 2022 GitHub, Inc.
  Footer navigation
  Terms
  Privacy
  Sec